spring:
  application:
    name: api-service
  profiles:
    default: dev   # si no se especifica, arranca con dev
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info