spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/dataflow}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.springframework: INFO
  file:
    name: ${LOG_FILE:logs/api-service.log}
