spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: WARN   # menos ruido en tests
    org.springframework: WARN