spring:
  application:
    name: api-service
  profiles:
    default: dev   # si no se especifica, arranca con dev
  main:
    web-application-type: servlet
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
batch:
  validation:
    storage-path-exists: false
  incrementer: runId
server:
  port: 8080
management:
  endpoints:
    metrics:
      enabled: true
    exposure:
      include: health,info,metrics,prometheus
    base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    metrics:
      web:
        server:
          request:
            autotime:
              enabled: true
    tags:
      application: api-service
scheduling:
  enabled: false
app:
  batch:
    default-config-id: "00000000-0000-0000-0000-000000000001"

logging:
  level:
    root: INFO