services:
  postgres:
    image: postgres:16-alpine
    container_name: dataflow_pg
    environment:
      POSTGRES_DB: dataflow
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: