-- V0__spring_batch_metadata_v5.sql  (ESQUEMA NUEVO)
CREATE TABLE BATCH_JOB_INSTANCE(
    JOB_INSTANCE_ID BIGINT PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION(
    JOB_EXECUTION_ID BIGINT PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID),
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    JOB_CONFIGURATION_LOCATION VARCHAR(2500)
);

-- NUEVO layout de parámetros:
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS(
    JOB_EXECUTION_ID BIGINT NOT NULL REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID),
    PARAMETER_NAME  VARCHAR(100) NOT NULL,
    PARAMETER_TYPE  VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING     CHAR(1) NOT NULL
);

CREATE TABLE BATCH_STEP_EXECUTION(
    STEP_EXECUTION_ID BIGINT PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID),
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT(
    STEP_EXECUTION_ID BIGINT PRIMARY KEY REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID),
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT(
    JOB_EXECUTION_ID BIGINT PRIMARY KEY REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID),
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT
);

CREATE SEQUENCE BATCH_JOB_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 50;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 50;
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 50;
