name: Maven CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build, Test & Check coverage
        run: ./mvnw -B clean jacoco:prepare-agent test jacoco:report jacoco:check

      - name: Publish coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: '**/target/site/jacoco'
          retention-days: 30

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/target/surefire-reports'
          retention-days: 30

      - name: Build & static analysis
        run: mvn -B clean verify

      - name: Upload quality reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: '**/target/quality-reports'
          retention-days: 30